# required for sonar (https://docs.travis-ci.com/user/sonarqube/) and py37
dist: xenial

# required for docker and sonar
sudo: required

language: python

cache: pip

services:
  - docker

addons:
  sonarcloud:
    organization: "1a"
    token:
      secure: "HCrI3UKgzOMeOhSisYaVPdUUah+jLljut+8Wc+ZJsSeIBAIghZ0AFkRJlm3zJqJjZkHeNxf6BhCw6ZFM7vdnQrBtaIK6Zwh/0N3hcqqTcxbiDIudJ3Ez36NWnM5FXoulAP7LqqyUFiqLmHMf3s3WxfHatHaYS3gXCRBFGEL1kjvIREFp6iWy4qcDs/gxVunp6oeJ9vwgRCvk8vsUTM0PhkAm7l2CYA4i918vF7/6k1WHJc3igMQzA6AwnJ86oE9NIXvBQYEQMIhwb1uK0bknusm+72sW3Z7uW/EPj5z0uOcEhvGLk9Z/C5gmOiimCGvWZLuZXGAYme5x2NQHRUC88ilu+wOWLdQT8vxQiblPduk83IUuat8NEsFYHQ8f3xtS2kKF7y1n9CX9YgfY+nSznhyxV3o+pXiTE5wRbn2Tq8gxsTSYD4nQd2dnzTJzlmWCBBFsj1gqUUY48RN4E4UCYAfPG2lyCd8izPYdpYMYLN86KfRgNnojojkWux+RIhDTjW+srKZ5/awXh3FxFkKA8mKzTc09UMraMwOBI78oqRYmk8T2y2EU6adsjDbAcTNM+mNwwv1virVu6sFYk6zlUtdHkCpYRVCMSG3XMB4/VZSl50UvuL60p/3tTNcWZhYLAx7KmM71vXEL7xd8kYqC5j/ELlYhjzM7zqswxQROMnA="
      # SONAR_TOKEN as is (/!\ no VAR= /!\)
    
    # Activating comments on PRs
    github_token:
      secure: "bm7Z0+qIbJ/j/bdRW/2NhqDdhQxmSq2lHDlde4QOu/wGi0nxsH8EdeB0Xo7Gn4jggjQnthXU/yNJ43xwRQk191eZ+vpGMKxiJIokcTPmd6ECtFGfwUnHFmFzmZwYQ4ehXpZA+kdqbz33gQrKqHz11ywn9t4p5Kt+WGGe2nTjmvXyryNUJj/jlxbcAFrUXSef31fKKsv9QvRpvtVSF1bOc/Yorb67mpNL06CwgA6lFAeLVB2V+ie6LdSociWf8I6cWv5n2gLPIzomlDXkJcq3Vmqk5U+oAPCvZQqqakzzvIueSP5IWp8YsVA41EFQWNU2cirsnvu78KbDwb2X6AY8rS7rXlYAip+Hst8yhlfhJKk/W2sI5kiITvgz6J7MKtmMVsDGYKExaslDifpFUfNoo6/s6gkMouqS6nZuDY6KybFgbL4dTjLtzmMpw1gQDJpVgwf+N6S/2atU2Suz+ukBCRh4WuE0c+FA29i5AVB3YUXmdG5d3CC6IqcmZ5R1DkIAE7pfharh/YRV47byEFcF5lMPY75hwdUjMQbI/k/w+XRLJTKllvGcbfUmZg7dFSsiK0OOoJV8iFfRXYSC4ropKNoNHonEo0FS3rDGN8+M8VrvX55r4/mHZK8dT5BxtYzPBNbrODsHLmQ6tKsEGgJCZym0+4E61M8goFPPoIgNXuI="

os:
  - linux

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - &pypy2 pypy2.7-6.0
  - &pypy3 pypy3.5-6.0

matrix:
  include:
    - python: 3.7
      env: TOX_ENV=flake8
    - python: 3.7
      env: TOX_ENV=docs

install:
  - pip install tox-travis coveralls

script:
  # if custom env specified, use it else just use current environment parameters
  - if [ -n "${TOX_ENV}" ]; then
      tox -e $TOX_ENV;
    else
      tox;
    fi
  - ./.travis/runSonarQubeAnalysis.sh

after_success:
  - coveralls

deploy:
  # deploys to PyPI on any tagged commit
  - provider: pypi
    user: tcastaing
    password:
      secure: "n0yaHnRh3gomvI2zFjyTZVHgKAinK0JEIIltUdnmj9LWjHb4JDpTKSx1lXZMpRop3ZJHMWFBeUtsZZinH3uu4yuoa8TlRC65CdGGbW/hSVuk1QcUGG2u1/5Rgenv/hVruaSU+iHwbjYtr3sCmSSnd8cS4IsDk1B3/zs1aTjKzMI5D6AjpCB2s/7+40s4y0qwETj8QXL1RbD5x5gEw7X0R/onImokP7DEuDVtOyKkqeqbPQZ+uNj4vqucg5GATOG6VI9m+jDyr/QAPZ/0HBf3XCH6/YaMpcekwKTApM9Y99zLOuvK3bwwrgd5b72HEppPzTn83RxAePs6EXGsoS5nQILUBs/7lKUpYMeWw8CzWtJUWn/Y9wxYcs79sIwTWgYLfWm0ZOb5hCmEfNmL9+vANQUzmI4FkE9Wa2FosT81SnuI/s2aBK4LgHDWqNd9WWv2rWHZNU2v4ZnFd4YdkwNj2OCecJQ+khrzzZp2U40fVN171YrKiVD67/T1mjvVYywFLpOh3HI72K81VeKXpJS1P9OQ6dLo3yD3lZsQyhlyKP1LbWvmbC3vgzay/xggW1UNQ4triiQtq3kqAexxvgcitKGQn9AC3z/ASkclEx0YjqDBONZOTiqWbYNjTXJkytZyPF7ht1U5FLJR+MltsD41NNNHopckPTCX3wUWalrDpTM="
    on:
      tags: true
      distributions: sdist bdist_wheel
      repo: AmadeusITGroup/JumpSSH
    # Upload artifacts only once
    skip_existing: true
