# required for sonar (https://docs.travis-ci.com/user/sonarqube/)
dist: trusty

# required for docker and sonar
sudo: required

language: python

services:
  - docker

addons:
  sonarqube:
    organization: "1a"
    token:
      secure: "HCrI3UKgzOMeOhSisYaVPdUUah+jLljut+8Wc+ZJsSeIBAIghZ0AFkRJlm3zJqJjZkHeNxf6BhCw6ZFM7vdnQrBtaIK6Zwh/0N3hcqqTcxbiDIudJ3Ez36NWnM5FXoulAP7LqqyUFiqLmHMf3s3WxfHatHaYS3gXCRBFGEL1kjvIREFp6iWy4qcDs/gxVunp6oeJ9vwgRCvk8vsUTM0PhkAm7l2CYA4i918vF7/6k1WHJc3igMQzA6AwnJ86oE9NIXvBQYEQMIhwb1uK0bknusm+72sW3Z7uW/EPj5z0uOcEhvGLk9Z/C5gmOiimCGvWZLuZXGAYme5x2NQHRUC88ilu+wOWLdQT8vxQiblPduk83IUuat8NEsFYHQ8f3xtS2kKF7y1n9CX9YgfY+nSznhyxV3o+pXiTE5wRbn2Tq8gxsTSYD4nQd2dnzTJzlmWCBBFsj1gqUUY48RN4E4UCYAfPG2lyCd8izPYdpYMYLN86KfRgNnojojkWux+RIhDTjW+srKZ5/awXh3FxFkKA8mKzTc09UMraMwOBI78oqRYmk8T2y2EU6adsjDbAcTNM+mNwwv1virVu6sFYk6zlUtdHkCpYRVCMSG3XMB4/VZSl50UvuL60p/3tTNcWZhYLAx7KmM71vXEL7xd8kYqC5j/ELlYhjzM7zqswxQROMnA="
      # SONAR_TOKEN as is (/!\ no VAR= /!\)

python: 3.6
env:
  matrix:
    - TOX_ENV=flake8
    - TOX_ENV=docs
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=py36
    - TOX_ENV=pypy

  global:
    # GITHUB_TOKEN
    - secure: "Br8mZxiBxGBH34FRGIxkXsYkPLL1tIVf1SSpvgOEYWGbvO910+UAnhpow+eufS9zqVOYUQIUA0PfEVd2EoCIgf6WHNsLOJRrEMkOyxd2SCgXsVaZu1f1TszfjCHEcAard0mwn2KrNEyR0DnB6xujHiY+O0LIdz7yicwh1BQd43wZaOYOpy3ohs969OOZ2Le6rfOMHCJY1Bsa018bwVwUB8Re3tAqsh+TCMVwWxhXfvZdTXe7kOMsjwh1a3TbcuIFFvfP/FxDqfJ0NJ1OLUmxvGVLXAnZHamPBgifSDQcu/BkxNcVQbLH3Pb7lo3Nx1ywr+LbXynC//xYQTn+0Ky9dSUrTZ+RDyRzvDxXs7fGttA2T67pBqWN8WUtZ5HXKr1GJa3WsCPzMgXegBfY1qiMvFRbRmjnV118xeOtOiLm1HHq4imxVGyLV23IvK9WBvZknouWHqWDYPWi5AbHQZ0Wk1oovIIS+Z3uDei5I77mzIk1D73wkgc0vNsNKdkFNMPMj94iRW945M768Ef4Qb0Oz/VWmHEsuMJycx3A8enXjC/tw14AVJKDJqlcoI/2UZZ5fBEIpOaSfBc6sQxVg0OgJ9/3aMF0RAYs2048jX02raoCKNVGBv/PPTop5hfQvdZ13ifkugPUnWszFXisa7VpP8AQklrFBU81jGJCNfPAl+g="



install:
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV
  - ./.travis/runSonarQubeAnalysis.sh

after_success:
  - coveralls

deploy:
  # deploys to PyPI on any tagged commit
  - provider: pypi
    user: tcastaing
    password:
      secure: "SQogu9XzcnplQBLWXqo2qwZBUpgInKflrei6BdTaYbxmCtdbCmev7H9OHBBXzzPe8R5WjjKqKNw6rFBJP2kAp2pS9KNJi1BfhHNvvs4JDgt4xUQ6hlcvyBAV+/L+EslIcXgm4AjEGBCn6G+4i9dwonYgl1iMIh0DAgRGQHexnyKDWpxlsgdH3TInwC2vZuZARAGhvzy3KB/X1nBNa6wbD7qEVTMiHmEEIZINS3PG6SGcaBSYSJaOPi2f7/MWLhzxXgKfWJgNpPNrMzlHJ4J7GSHlUlsLVZKaYoBihPa5+e6dkVKh8qrxJBIZe4y5kKuY+sRtlslFwbVQj8dE6T5rdiPLuBDhTkTL98tVAgHrKZjmhZ97sak/iPr14yHAk5K9hgEh+wsI8w48Edhk4KA+MmQA4lhPUzFW0Fm9jqVkpowNjc4NgAcGK009cW1+ZjlZnQFwIzfoYgbKsyisGwdclVHAotpxnibZqBfza0AXhbeX+5w+ZEF92gqvjdvG6dMWiQdplRWyYScpAq/1c2L8EkhXYfk8i8Jl+LkuH2xoRfEdG0Vr/EpW1omThkwGz2v6QPd29p1EgI4hiJ7GsmQvf8DoPejMW46QibZWKENIxkN2md9UzIKQEuNo7mf2pXGUgfdXtxjIC8AnHyoYCyqpjSPeBMi1uKQYLI/wnGpckDY="
    on:
      tags: true
      distributions: sdist bdist_wheel
      repo: AmadeusITGroup/JumpSSH
